name: Generate Lanyard Badges
on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  generate-badges:
    runs-on: ubuntu-latest
    permissions: 
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Fetch Discord Data from Lanyard
        run: |
          DATA=$(curl -s https://api.lanyard.rest/v1/users/788036014202945546)

          # Get Discord Status
          STATUS=$(echo $DATA | jq -r '.data.discord_status')
          if [[ "$STATUS" == "online" ]]; then 
            COLOR="brightgreen"
            STATUS_TEXT="Online"
          elif [[ "$STATUS" == "idle" ]]; then 
            COLOR="yellow"
            STATUS_TEXT="Idle"
          elif [[ "$STATUS" == "dnd" ]]; then 
            COLOR="red"
            STATUS_TEXT="Do Not Disturb"
          else 
            COLOR="lightgrey"
            STATUS_TEXT="Offline"
          fi
          echo "<svg xmlns='http://www.w3.org/2000/svg' width='200' height='30'><rect width='200' height='30' fill='$COLOR'/><text x='50%' y='20' fill='white' font-size='14' text-anchor='middle'>Discord: $STATUS_TEXT</text></svg>" > discord-status.svg
          
          # Get Spotify Status
          SPOTIFY=$(echo $DATA | jq -r '.data.spotify.track_id')
          if [[ "$SPOTIFY" != "null" ]]; then
            SONG=$(echo $DATA | jq -r '.data.spotify.song')
            COLOR="brightgreen"
          else
            SONG="Not Listening"
            COLOR="lightgrey"
          fi
          echo "<svg xmlns='http://www.w3.org/2000/svg' width='200' height='30'><rect width='200' height='30' fill='$COLOR'/><text x='50%' y='20' fill='white' font-size='14' text-anchor='middle'>Spotify: $SONG</text></svg>" > spotify-status.svg
          
          # Get VS Code Status
          EDITOR=$(echo $DATA | jq -r '.data.activities[] | select(.name=="Visual Studio Code") | .name')
          if [[ "$EDITOR" == "Visual Studio Code" ]]; then
            VS_TEXT="Coding in VS Code"
            COLOR="blue"
          else
            VS_TEXT="Not Coding"
            COLOR="lightgrey"
          fi
          echo "<svg xmlns='http://www.w3.org/2000/svg' width='200' height='30'><rect width='200' height='30' fill='$COLOR'/><text x='50%' y='20' fill='white' font-size='14' text-anchor='middle'>$VS_TEXT</text></svg>" > vscode-status.svg

      - name: Commit and Push Badges
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add discord-status.svg spotify-status.svg vscode-status.svg
          git commit -m "Update Discord, Spotify, and VS Code badges" || exit 0
          git push
