name: Update Lanyard Badges
on:
  schedule:
    - cron: "*/5 * * * *"  # Run every 5 minutes
  workflow_dispatch:  # Allow manual trigger

jobs:
  update-badges:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Allow writing to the repo
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Fetch Lanyard Data
        run: |
          # Fetch data from Lanyard API
          DATA=$(curl -s https://api.lanyard.rest/v1/users/788036014202945546)
          
          # Update Discord Status Badge
          STATUS=$(echo $DATA | jq -r '.data.discord_status')
          if [[ "$STATUS" == "online" ]]; then
            DISCORD_BADGE="https://img.shields.io/badge/Discord-Online-brightgreen?logo=discord"
          elif [[ "$STATUS" == "idle" ]]; then
            DISCORD_BADGE="https://img.shields.io/badge/Discord-Idle-yellow?logo=discord"
          elif [[ "$STATUS" == "dnd" ]]; then
            DISCORD_BADGE="https://img.shields.io/badge/Discord-Do_Not_Disturb-red?logo=discord"
          else
            DISCORD_BADGE="https://img.shields.io/badge/Discord-Offline-lightgrey?logo=discord"
          fi

          # Update Spotify Status Badge
          SPOTIFY=$(echo $DATA | jq -r '.data.spotify.song // empty')
          if [[ -n "$SPOTIFY" ]]; then
            SPOTIFY_BADGE="https://img.shields.io/badge/Spotify-Listening_to_${SPOTIFY// /_}-brightgreen?logo=spotify"
          else
            SPOTIFY_BADGE="https://img.shields.io/badge/Spotify-Not_Listening-lightgrey?logo=spotify"
          fi

          # Update VS Code Status Badge
          CODING_ACTIVITY=$(echo "$DATA" | jq -r '.data.activities[]? | select(.name=="Visual Studio Code") | .state' || echo "")
          if [[ "$CODING_ACTIVITY" == "Editing" || "$CODING_ACTIVITY" == "Working on a project" ]]; then
            VS_BADGE="https://img.shields.io/badge/VS_Code-Coding-blue?logo=visualstudiocode"
          elif [[ -n "$CODING_ACTIVITY" ]]; then
            VS_BADGE="https://img.shields.io/badge/VS_Code-Idle-yellow?logo=visualstudiocode"
          else
            VS_BADGE="https://img.shields.io/badge/VS_Code-Not_Coding-lightgrey?logo=visualstudiocode"
          fi

          # Update README.md badges in <img> tags
          sed -i "s|<img src=\"https://img.shields.io/badge/Discord-.*?logo=discord\"|<img src=\"$DISCORD_BADGE\"|g" README.md
          sed -i "s|<img src=\"https://img.shields.io/badge/Spotify-.*?logo=spotify\"|<img src=\"$SPOTIFY_BADGE\"|g" README.md
          sed -i "s|<img src=\"https://img.shields.io/badge/VS_Code-.*?logo=visualstudiocode\"|<img src=\"$VS_BADGE\"|g" README.md

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add README.md
          git commit -m "Update Lanyard status badges" || exit 0
          git push
